# Generated by Django 3.2.23 on 2023-12-13 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_post_picture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at'], 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.AddField(
            model_name='post',
            name='image_filter',
            field=models.CharField(blank=True, choices=[('normal', 'Normal'), ('black_and_white', 'Black and White'), ('sepia', 'Sepia'), ('vintage', 'Vintage'), ('grayscale', 'Grayscale'), ('warm', 'Warm Tone'), ('cool', 'Cool Tone'), ('invert', 'Invert Colors'), ('blur', 'Blur'), ('sharpen', 'Sharpen')], default='normal', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='header',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
