# Generated by Django 3.2.23 on 2023-12-14 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0002_alter_like_post'),
        ('posts', '0003_auto_20231213_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_posts', to='likes.Like'),
        ),
    ]
